spring:
  application:
    name: tips-service

server:
  port: 8083

jwt:
  secret: mySecretKeyForJWTTokenGenerationAndValidation12345678901234567890
  security:
    enabled: true  # Enable JWT security

logging:
  level:
    com.multiservice: DEBUG
