input {
  tcp {
    port => 5010
    codec => json_lines
  }
}

filter {
  # Parse the JSON message (already structured from logback)
#   json {
#     source => "message"
#     target => "parsed_message"
#   }

  # Add additional metadata
  mutate {
    add_field => {
      "[@metadata][index]" => "microservices-logs-%{+YYYY.MM.dd}"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "microservices-logs-%{+YYYY.MM.dd}"
  }

  # Optional: output to console for debugging
  stdout {
    codec => rubydebug
  }
}